name: MacOS

on:
  push:
    branches:
      - master
      - setup-ci
      - feature/cmake-presets
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"
          host: mac
          target: desktop
          arch: clang_64

      - name: Configure CMake
        run: cmake --preset macos -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=OFF -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""

      - name: Build the library.
        run: cmake --build --preset macos

      - name: Build the Sandbox app.
        run: cmake --build --preset macos-sandbox
